api:
  paypal:
    url: "sb-ogq9625033190@business.example.com"
    token: "access_token$sandbox$rwhzdn6jvqq7hktv$8ea3e15072663fd0c1858750b39b0fa0"
    clientId: "ARPO7-v-GSqOFvqloH5NhDrBLaBI7GiveEzFE36v5KTK9zEw4F2RsiAr_BBVgPCjNvT6FDiyQXJmSRvq"
    clientSecret: "EDz_9KSkxbzgc-AlKFr2N7_Rnghbfb7U7UXwU25KiI_bKvvSqqg93oI5UKuwcEmenA9ubHNP3bzwZsKi"
    mode: "sandbox"
  stripe:
    token: "pk_test_51MaLigE6L6fXv5FL9UdngK2KtbB4OLZZBBWahpjZZWhWW3nW7uPPIz8ilqCnH9upUkdAzeTpaKFkbDyxyTHmlgou00akUrb82m"
    secretKey: "sk_test_51MaLigE6L6fXv5FLOH5684HxlzOkQMKlPDO0Ld5xYLXZPWnTm4AHyN3xEwEttdVb5Pj8TXuAOPrKDa0Hk8joddB500I0pjZFmM"
server:
  port: 8081
