api:
  paypal:
    clientId: ${PAYPAL_CLIENT_ID}
    clientSecret: ${PAYPAL_CLIENT_SECRET}
  stripe:
    secretKey: ${STRIPE_SECRET_KEY}
  twilio:
    accountSid: "AC034587118e27cdbda3189996015531f9"
    authToken: "5c1378db47f788bcc3360fa3226b123f"
    verifyTemplateId: "VA3aa82f42abc0c33c0ea9a2f45a2b16ba"
    otpCode: "123456"
server:
  port: 8081
