api:
  paypal:
    mode: "sandbox"
    clientId: ${PAYPAL_CLIENT_ID}
    clientSecret: ${PAYPAL_CLIENT_SECRET}
  stripe:
    secretKey: ${STRIPE_SECRET_KEY}
  swell:
    storeId: ${SWELL_STORE_ID}
    secretKey: ${SWELL_SECRET_KEY}
    host: "api.swell.store"
    port: 8443
  twilio:
    accountSid: ${TWILIO_ACCOUNT_SID}
    authToken: ${TWILIO_AUTH_TOKEN}
    templateSid: ${TWILIO_TEMPLATE_SID}
server:
  port: 8081
frontend:
  server:
    url: ${FRONT_END_URL}
spring:
  profiles:
    active: dev
